import { Box, Container, Heading, Text } from '@chakra-ui/react'
import { Sidebar } from '@/components/Sidebar'
import { Header } from '@/components/Header'
import { MarkdownContent } from '@/components/MarkdownContent'

export const metadata = {
  title: 'Persistence Docs - Next.js Website - Persistence Docs',
  description: '',
}

export default function Page() {
  const content = `# Persistence Docs - Next.js Website

This is the Next.js version of the Persistence documentation, converted from GitBook.

## Setup Instructions

### 1. Install Dependencies

\`\`\`bash
npm install
\`\`\`

### 2. Migrate Content

Run the migration script to copy all markdown files to the \`content\` directory:

\`\`\`bash
node scripts/migrate-content.js
\`\`\`

This will:
- Copy all \`.md\` files from the project root and subdirectories to \`content/\`
- Preserve the directory structure
- Exclude build files, node_modules, and other non-content files

### 3. Run Development Server

\`\`\`bash
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) to view the documentation.

### 4. Build for Production

\`\`\`bash
npm run build
npm start
\`\`\`

## Project Structure

\`\`\`
persistence-docs/
├── app/                    # Next.js app directory
│   ├── docs/              # Documentation pages
│   └── layout.tsx         # Root layout
├── components/            # React components
│   ├── Sidebar.tsx        # Navigation sidebar
│   ├── MarkdownContent.tsx # Markdown renderer
│   └── Providers.tsx      # Chakra UI provider
├── content/               # Markdown files (generated by migration script)
├── lib/                   # Utilities
│   ├── markdown.ts       # Markdown processing
│   └── navigation.ts     # Navigation structure
├── theme/                 # Chakra UI theme
└── scripts/             # Migration scripts
\`\`\`

## Features

- ✅ Next.js 14 with App Router
- ✅ TypeScript
- ✅ Chakra UI for styling
- ✅ Markdown rendering with syntax highlighting
- ✅ GitBook syntax conversion (hints, embeds, content-refs)
- ✅ Responsive sidebar navigation
- ✅ Dynamic routing for all documentation pages

## GitBook Syntax Conversion

The following GitBook syntax is automatically converted:

- \`{% hint style="info" %}\` → Alert boxes with appropriate styling
- \`{% content-ref url="..." %}\` → Internal links
- \`<div class="embed-container"><iframe src="..." frameborder="0" allowfullscreen></iframe></div>\` → Embedded content links
- \`data-view="cards"\` → Regular tables
- Relative markdown links → Absolute \`/docs/\` paths

## Customization

### Navigation

Edit \`lib/navigation.ts\` to update the sidebar navigation structure.

### Styling

Edit \`theme/index.ts\` to customize Chakra UI theme.

### Markdown Processing

Edit \`lib/markdown.ts\` to customize GitBook syntax conversion.

## Deployment

This project can be deployed to:
- Vercel (recommended for Next.js)
- Netlify
- Any Node.js hosting platform

For static export, you may need to configure Next.js for static site generation.

`
  const hideFirstHeading = true

  return (
    <Box display="flex" flexDirection="column" height="100vh" overflow="hidden">
      <Header />
      <Box display="flex" flex="1" overflow="hidden">
        <Sidebar />
        <Box flex="1" bg="white" overflowY="auto" overflowX="hidden">
          <Container maxW="5xl" py={8} px={7}>
          {hideFirstHeading && (
            <Heading as="h1" size="2xl" mb={4}>
              Persistence Docs - Next.js Website
            </Heading>
          )}
          
          <MarkdownContent content={content} hideFirstHeading={hideFirstHeading} />
          </Container>
        </Box>
      </Box>
    </Box>
  )
}
